// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Event event
//
// swagger:model Event
type Event struct {

	// days amount till notify
	// Example: 5
	DaysAmountTillNotify int64 `json:"daysAmountTillNotify,omitempty"`

	// description
	// Example: description
	Description string `json:"description,omitempty"`

	// end
	// Example: 1900-01-01
	// Format: date
	End strfmt.Date `json:"end,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// owner Id
	// Example: 1
	OwnerID int64 `json:"ownerId,omitempty"`

	// start
	// Example: 1900-01-01
	// Format: date
	Start strfmt.Date `json:"start,omitempty"`

	// title
	// Example: Event
	Title string `json:"title,omitempty"`
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStart(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Event) validateEnd(formats strfmt.Registry) error {
	if swag.IsZero(m.End) { // not required
		return nil
	}

	if err := validate.FormatOf("end", "body", "date", m.End.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Event) validateStart(formats strfmt.Registry) error {
	if swag.IsZero(m.Start) { // not required
		return nil
	}

	if err := validate.FormatOf("start", "body", "date", m.Start.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this event based on context it is used
func (m *Event) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Event) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Event) UnmarshalBinary(b []byte) error {
	var res Event
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
