// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventCreated event created
//
// swagger:model EventCreated
type EventCreated struct {

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`
}

// Validate validates this event created
func (m *EventCreated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event created based on context it is used
func (m *EventCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventCreated) UnmarshalBinary(b []byte) error {
	var res EventCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
