run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 200
    statements: 80

issues:
  exclude-rules:
    - path: ".*swagger.*"
      linters:
        - glint
        - revive
        - lll
    - path: ".*restapi.*"
      linters:
        - glint
        - revive
        - lll
    - path: ".*models.*"
      linters:
        - glint
        - revive
        - lll
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
    - path: /opt/hostedtoolcache/go/.*\.go
      linters:
        - typecheck
    - path: ../../../../go/pkg/mod/.*\.go
      linters:
        - typecheck


linters:
  disable-all: true
  enable:
    - asciicheck
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
