// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RollerM0bster/hw-esheludenko/hw12_13_14_15_calendar/models"
)

// DeleteEventsIDNoContentCode is the HTTP code returned for type DeleteEventsIDNoContent
const DeleteEventsIDNoContentCode int = 204

/*
DeleteEventsIDNoContent Успех

swagger:response deleteEventsIdNoContent
*/
type DeleteEventsIDNoContent struct {
}

// NewDeleteEventsIDNoContent creates DeleteEventsIDNoContent with default headers values
func NewDeleteEventsIDNoContent() *DeleteEventsIDNoContent {

	return &DeleteEventsIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteEventsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteEventsIDNotFoundCode is the HTTP code returned for type DeleteEventsIDNotFound
const DeleteEventsIDNotFoundCode int = 404

/*
DeleteEventsIDNotFound Событие не найдено

swagger:response deleteEventsIdNotFound
*/
type DeleteEventsIDNotFound struct {
}

// NewDeleteEventsIDNotFound creates DeleteEventsIDNotFound with default headers values
func NewDeleteEventsIDNotFound() *DeleteEventsIDNotFound {

	return &DeleteEventsIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteEventsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteEventsIDInternalServerErrorCode is the HTTP code returned for type DeleteEventsIDInternalServerError
const DeleteEventsIDInternalServerErrorCode int = 500

/*
DeleteEventsIDInternalServerError Ошибка

swagger:response deleteEventsIdInternalServerError
*/
type DeleteEventsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteEventsIDInternalServerError creates DeleteEventsIDInternalServerError with default headers values
func NewDeleteEventsIDInternalServerError() *DeleteEventsIDInternalServerError {

	return &DeleteEventsIDInternalServerError{}
}

// WithPayload adds the payload to the delete events Id internal server error response
func (o *DeleteEventsIDInternalServerError) WithPayload(payload *models.Error) *DeleteEventsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete events Id internal server error response
func (o *DeleteEventsIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteEventsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
