// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RollerM0bster/hw-esheludenko/hw12_13_14_15_calendar/models"
)

// GetEventsByWeekOKCode is the HTTP code returned for type GetEventsByWeekOK
const GetEventsByWeekOKCode int = 200

/*
GetEventsByWeekOK Успех

swagger:response getEventsByWeekOK
*/
type GetEventsByWeekOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Event `json:"body,omitempty"`
}

// NewGetEventsByWeekOK creates GetEventsByWeekOK with default headers values
func NewGetEventsByWeekOK() *GetEventsByWeekOK {

	return &GetEventsByWeekOK{}
}

// WithPayload adds the payload to the get events by week o k response
func (o *GetEventsByWeekOK) WithPayload(payload []*models.Event) *GetEventsByWeekOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events by week o k response
func (o *GetEventsByWeekOK) SetPayload(payload []*models.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsByWeekOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Event, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetEventsByWeekInternalServerErrorCode is the HTTP code returned for type GetEventsByWeekInternalServerError
const GetEventsByWeekInternalServerErrorCode int = 500

/*
GetEventsByWeekInternalServerError Ошибка

swagger:response getEventsByWeekInternalServerError
*/
type GetEventsByWeekInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetEventsByWeekInternalServerError creates GetEventsByWeekInternalServerError with default headers values
func NewGetEventsByWeekInternalServerError() *GetEventsByWeekInternalServerError {

	return &GetEventsByWeekInternalServerError{}
}

// WithPayload adds the payload to the get events by week internal server error response
func (o *GetEventsByWeekInternalServerError) WithPayload(payload *models.Error) *GetEventsByWeekInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events by week internal server error response
func (o *GetEventsByWeekInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsByWeekInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
