// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/RollerM0bster/hw-esheludenko/hw12_13_14_15_calendar/models"
	"github.com/go-openapi/runtime"
)

// GetEventsByMonthOKCode is the HTTP code returned for type GetEventsByMonthOK
const GetEventsByMonthOKCode int = 200

/*
GetEventsByMonthOK Успех

swagger:response getEventsByMonthOK
*/
type GetEventsByMonthOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Event `json:"body,omitempty"`
}

// NewGetEventsByMonthOK creates GetEventsByMonthOK with default headers values
func NewGetEventsByMonthOK() *GetEventsByMonthOK {

	return &GetEventsByMonthOK{}
}

// WithPayload adds the payload to the get events by month o k response
func (o *GetEventsByMonthOK) WithPayload(payload []*models.Event) *GetEventsByMonthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events by month o k response
func (o *GetEventsByMonthOK) SetPayload(payload []*models.Event) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsByMonthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Event, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetEventsByMonthInternalServerErrorCode is the HTTP code returned for type GetEventsByMonthInternalServerError
const GetEventsByMonthInternalServerErrorCode int = 500

/*
GetEventsByMonthInternalServerError Ошибка

swagger:response getEventsByMonthInternalServerError
*/
type GetEventsByMonthInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetEventsByMonthInternalServerError creates GetEventsByMonthInternalServerError with default headers values
func NewGetEventsByMonthInternalServerError() *GetEventsByMonthInternalServerError {

	return &GetEventsByMonthInternalServerError{}
}

// WithPayload adds the payload to the get events by month internal server error response
func (o *GetEventsByMonthInternalServerError) WithPayload(payload *models.Error) *GetEventsByMonthInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get events by month internal server error response
func (o *GetEventsByMonthInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEventsByMonthInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
