// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventsByMonthHandlerFunc turns a function with the right signature into a get events by month handler
type GetEventsByMonthHandlerFunc func(GetEventsByMonthParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventsByMonthHandlerFunc) Handle(params GetEventsByMonthParams) middleware.Responder {
	return fn(params)
}

// GetEventsByMonthHandler interface for that can handle valid get events by month params
type GetEventsByMonthHandler interface {
	Handle(GetEventsByMonthParams) middleware.Responder
}

// NewGetEventsByMonth creates a new http.Handler for the get events by month operation
func NewGetEventsByMonth(ctx *middleware.Context, handler GetEventsByMonthHandler) *GetEventsByMonth {
	return &GetEventsByMonth{Context: ctx, Handler: handler}
}

/*
	GetEventsByMonth swagger:route GET /events-by-month getEventsByMonth

Получить все события за месяц
*/
type GetEventsByMonth struct {
	Context *middleware.Context
	Handler GetEventsByMonthHandler
}

func (o *GetEventsByMonth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventsByMonthParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
