// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEventsByWeekParams creates a new GetEventsByWeekParams object
//
// There are no default values defined in the spec.
func NewGetEventsByWeekParams() GetEventsByWeekParams {

	return GetEventsByWeekParams{}
}

// GetEventsByWeekParams contains all the bound params for the get events by week operation
// typically these are obtained from a http.Request
//
// swagger:parameters getEventsByWeek
type GetEventsByWeekParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Дата начала недели
	  Required: true
	  In: query
	*/
	WeekStart strfmt.Date
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEventsByWeekParams() beforehand.
func (o *GetEventsByWeekParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qWeekStart, qhkWeekStart, _ := qs.GetOK("weekStart")
	if err := o.bindWeekStart(qWeekStart, qhkWeekStart, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWeekStart binds and validates parameter WeekStart from query.
func (o *GetEventsByWeekParams) bindWeekStart(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("weekStart", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("weekStart", "query", raw); err != nil {
		return err
	}

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("weekStart", "query", "strfmt.Date", raw)
	}
	o.WeekStart = *(value.(*strfmt.Date))

	if err := o.validateWeekStart(formats); err != nil {
		return err
	}

	return nil
}

// validateWeekStart carries on validations for parameter WeekStart
func (o *GetEventsByWeekParams) validateWeekStart(formats strfmt.Registry) error {

	if err := validate.FormatOf("weekStart", "query", "date", o.WeekStart.String(), formats); err != nil {
		return err
	}
	return nil
}
