// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEventsByWeekHandlerFunc turns a function with the right signature into a get events by week handler
type GetEventsByWeekHandlerFunc func(GetEventsByWeekParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEventsByWeekHandlerFunc) Handle(params GetEventsByWeekParams) middleware.Responder {
	return fn(params)
}

// GetEventsByWeekHandler interface for that can handle valid get events by week params
type GetEventsByWeekHandler interface {
	Handle(GetEventsByWeekParams) middleware.Responder
}

// NewGetEventsByWeek creates a new http.Handler for the get events by week operation
func NewGetEventsByWeek(ctx *middleware.Context, handler GetEventsByWeekHandler) *GetEventsByWeek {
	return &GetEventsByWeek{Context: ctx, Handler: handler}
}

/*
	GetEventsByWeek swagger:route GET /events-by-week getEventsByWeek

Получить все события за неделю
*/
type GetEventsByWeek struct {
	Context *middleware.Context
	Handler GetEventsByWeekHandler
}

func (o *GetEventsByWeek) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEventsByWeekParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
