// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RollerM0bster/hw-esheludenko/hw12_13_14_15_calendar/models"
)

// PostEventsCreatedCode is the HTTP code returned for type PostEventsCreated
const PostEventsCreatedCode int = 201

/*
PostEventsCreated Событие успешно создано

swagger:response postEventsCreated
*/
type PostEventsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.EventCreated `json:"body,omitempty"`
}

// NewPostEventsCreated creates PostEventsCreated with default headers values
func NewPostEventsCreated() *PostEventsCreated {

	return &PostEventsCreated{}
}

// WithPayload adds the payload to the post events created response
func (o *PostEventsCreated) WithPayload(payload *models.EventCreated) *PostEventsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post events created response
func (o *PostEventsCreated) SetPayload(payload *models.EventCreated) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEventsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostEventsInternalServerErrorCode is the HTTP code returned for type PostEventsInternalServerError
const PostEventsInternalServerErrorCode int = 500

/*
PostEventsInternalServerError Ошибка

swagger:response postEventsInternalServerError
*/
type PostEventsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostEventsInternalServerError creates PostEventsInternalServerError with default headers values
func NewPostEventsInternalServerError() *PostEventsInternalServerError {

	return &PostEventsInternalServerError{}
}

// WithPayload adds the payload to the post events internal server error response
func (o *PostEventsInternalServerError) WithPayload(payload *models.Error) *PostEventsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post events internal server error response
func (o *PostEventsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEventsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
