// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutEventsIDHandlerFunc turns a function with the right signature into a put events ID handler
type PutEventsIDHandlerFunc func(PutEventsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutEventsIDHandlerFunc) Handle(params PutEventsIDParams) middleware.Responder {
	return fn(params)
}

// PutEventsIDHandler interface for that can handle valid put events ID params
type PutEventsIDHandler interface {
	Handle(PutEventsIDParams) middleware.Responder
}

// NewPutEventsID creates a new http.Handler for the put events ID operation
func NewPutEventsID(ctx *middleware.Context, handler PutEventsIDHandler) *PutEventsID {
	return &PutEventsID{Context: ctx, Handler: handler}
}

/*
	PutEventsID swagger:route PUT /events/{id} putEventsId

Обновить событие
*/
type PutEventsID struct {
	Context *middleware.Context
	Handler PutEventsIDHandler
}

func (o *PutEventsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutEventsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
