// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RollerM0bster/hw-esheludenko/hw12_13_14_15_calendar/models"
)

// PutEventsIDNoContentCode is the HTTP code returned for type PutEventsIDNoContent
const PutEventsIDNoContentCode int = 204

/*
PutEventsIDNoContent Событие успешно обновлено

swagger:response putEventsIdNoContent
*/
type PutEventsIDNoContent struct {
}

// NewPutEventsIDNoContent creates PutEventsIDNoContent with default headers values
func NewPutEventsIDNoContent() *PutEventsIDNoContent {

	return &PutEventsIDNoContent{}
}

// WriteResponse to the client
func (o *PutEventsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutEventsIDInternalServerErrorCode is the HTTP code returned for type PutEventsIDInternalServerError
const PutEventsIDInternalServerErrorCode int = 500

/*
PutEventsIDInternalServerError Ошибка

swagger:response putEventsIdInternalServerError
*/
type PutEventsIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutEventsIDInternalServerError creates PutEventsIDInternalServerError with default headers values
func NewPutEventsIDInternalServerError() *PutEventsIDInternalServerError {

	return &PutEventsIDInternalServerError{}
}

// WithPayload adds the payload to the put events Id internal server error response
func (o *PutEventsIDInternalServerError) WithPayload(payload *models.Error) *PutEventsIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put events Id internal server error response
func (o *PutEventsIDInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutEventsIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
