swagger: "2.0"
info:
  title: Calendar API
  description: API для работы с событиями календаря
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
paths:
  /events:
    post:
      summary: Создать новое событие
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewEvent'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '201':
          description: Событие успешно создано
          schema:
            type : object
            properties:
              id:
                type: integer
                description: Идентификатор события
            $ref: '#/definitions/EventCreated'
        '500':
          description: Ошибка
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Обновить событие
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewEvent'
      responses:
        '204':
          description: Событие успешно обновлено
        '500':
          description: Ошибка
          schema:
            $ref: '#/definitions/Error'
  /events/{id}:
    delete:
      summary: Удалить событие по идентификатору
      parameters:
        - name: id
          in: path
          required: true
          description: ID события
          type: string
      responses:
        '204':
          description: Успех
        '404':
          description: Событие не найдено
        '500':
          description: Ошибка
          schema:
            $ref: '#/definitions/Error'
  /events-by-week:
    get:
      summary: Получить все события за неделю
      operationId: getEventsByWeek
      parameters:
        - name: weekStart
          in: query
          description: Дата начала недели
          required: true
          type: string
          format: date
      responses:
        '200':
          description: Успех
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        '500':
          description: Ошибка
          schema:
            $ref: '#/definitions/Error'
  /events-by-day:
      get:
        summary: Получить все события за день
        operationId: getEventsByDay
        parameters:
          - name: date
            in: query
            description: Дата
            required: true
            type: string
            format: date
        responses:
          '200':
            description: Успех
            schema:
              type: array
              items:
                $ref: '#/definitions/Event'
          '500':
            description: Ошибка
            schema:
              $ref: '#/definitions/Error'
  /events-by-month:
      get:
        summary: Получить все события за месяц
        operationId: getEventsByMonth
        parameters:
          - name: date
            in: query
            description: Дата начала месяца
            required: true
            type: string
            format: date
        responses:
          '200':
            description: Успех
            schema:
              type: array
              items:
                $ref: '#/definitions/Event'
          '500':
            description: Ошибка
            schema:
              $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
  Event:
    type: object
    properties:
      id:
        type: integer
        example: 1
      title:
        type: string
        example: "Event"
      start:
        type: string
        format: date
        example: '1900-01-01'
      end:
        type: string
        format: date
        example: '1900-01-01'
      daysAmountTillNotify:
        type: integer
        example: 5
      description:
        type: string
        example: 'description'
      ownerId:
        type: integer
        example: 1
  NewEvent:
    type: object
    properties:
      title:
        type: string
        example: 'title'
      start:
        type: string
        format: date
        example: '1900-01-01'
      end:
        type: string
        format: date
        example: '1900-01-01'
      daysAmountTillNotify:
        type: integer
        example: 5
      description:
        type: string
        example: 'description'
      ownerId:
        type: integer
        example: 1
  EventCreated:
    type: object
    properties:
      id:
        type: integer
        example: 1
